In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/online-retail-dataset/Online Retail Cleaned.xlsx

In [2]:
df = pd.read_excel('/kaggle/input/online-retail-dataset/Online Retail Cleaned.xlsx')

In [3]:
df.head(5)

,InvoiceNumber,ProductCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalSales
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 824322 entries, 0 to 824321
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceNumber  824322 non-null  object
 1   ProductCode    824322 non-null  object
 2   Description    824322 non-null  object
 3   Quantity       824322 non-null  int64
 4   InvoiceDate    824322 non-null  datetime64[ns]
 5   Price          824322 non-null  float64
 6   Customer ID    824322 non-null  int64
 7   Country        824322 non-null  object
 8   TotalSales     824322 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 56.6+ MB

In [5]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,TotalSales
count,824322.000000,824322,824322.000000,824322.000000,824322.000000
mean,12.415443,2011-01-01 22:58:33.370405888,3.676738,15324.593362,20.197066
min,-80995.000000,2009-12-01 07:45:00,0.000000,12346.000000,-168469.600000
25%,2.000000,2010-07-06 12:01:00,1.250000,13975.000000,4.250000
50%,5.000000,2010-12-03 14:30:00,1.950000,15255.000000,11.250000
75%,12.000000,2011-07-27 15:17:00,3.750000,16797.000000,19.500000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,168469.600000
std,188.980871,NaN,70.243172,1697.473365,308.692763

In [6]:
print(f'Total Country: {df["Country"].nunique()}')
#df["Country"].unique()
sorted(df["Country"].unique())

Total Country: 41

['Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Eire',
 'European Community',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Korea',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Nigeria',
 'Norway',
 'Poland',
 'Portugal',
 'Rsa',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'Thailand',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified',
 'Usa',
 'West Indies']